# -*- coding: utf-8 -*-
"""PY525ACTUALFinalCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xAkPv48NHJJp5O0jKoiPy32rciXUwywe
"""

!gdown 1S24P5zHvjhS8AMr9_IbwP-sgs1HUEQIG
!unzip -o lib.zip

from lib.system import System
from lib.potential import V_Gauss
sys = System()
V = V_Gauss(sys, -4.0, 2.0)

import numpy as np
import scipy.integrate as si
import scipy.linalg as sl

class SVM:

    # This class is stores and manages all the aspects of the SVM

    def __init__(self, ms, rs, V, script_N, K_max, refine_max, bmin, bmax, V0=None, R=None):
        assert len(ms) == len(rs)
        # masses, positions and potential
        self.ms = np.array(ms)
        self.rs = np.array(rs)
        self.V = V
        # packing the gaussian parameters for potential optimization
        self.V0 = V0
        self.R = R
        self.gauss_params = (V0, R) if V is not None and R is not None else None
        # number of bodies
        self.N = len(ms)
        # cumulative masses for ease in computation, B_ijk, reduced masses, and jacobi coordinates
        self.cum_ms = np.cumsum(self.ms)
        self.B = self.generate_bijk()
        self.mus = self.masses_to_reduced()
        self.xs = self.positions_to_jacobi()
        # dimensions of A for readability, max and min on the uniform random values in A*
        self.dim = self.N - 1
        self.bmax = bmax
        self.bmin = bmin
        # number of candidates, max dimension of K, max times of refinement
        self.script_N = script_N
        self.K_max = K_max
        self.refine_max = refine_max
        # an K-length incrementally generating array of (N-1)x(N-1) matrices A, stored as a 3-d matrix, with the first index being K
        # just being initialized as a 0-size 3-d array
        self.A_i = np.empty((0,0,0))

    def main(self):

        # Generating Phase

        # The paper describes two methods called svm1 and svm2
        # We implemented a hybrid method that first runs svm1 in what we call the Generating Phase
        # This generates a K_max length array of A matrices incrementally
        # Then we pass that same array into an implementation of svm2 which we call the Refining Phase

        for K in range(1, self.K_max+1):
            # generates Script_N candidates for self.A_i, which is stored in a 4-d array with the first index being n
            vector_set = self.generate_set_A(K)
            # initializing values to hold the lowest found energy and the index that the energy is found
            E_K = np.inf
            idx_of_A_K_m = 0
            # iterating through every candidate
            for n in range(self.script_N):
                # generating Hamiltonian and Overlap matrices for a candidate
                Hij, Bij = self.create_Hij_and_Bij(K, vector_set[n])
                # finding the smallest eigenvalue
                E_K_n = np.min(sl.eigvals(Hij, Bij))
                # if the eigenvalue is smaller, rewrite the storing variables
                if E_K_n < E_K:
                    E_K = E_K_n
                    idx_of_A_K_m = n
            # finalize the candidate that generated the lowest energy value
            self.A_i = vector_set[idx_of_A_K_m]
            # print to monitor progress of code
            print("K:", K, "E_K:", E_K)

        # Refining Phase

        # refine refine_max times
        for _ in range(self.refine_max):
            # iterate through matrices in self.A_i
            for K in range(1, self.K_max+1):
                # calculate the energy value prior to refinement
                Hij, Bij = self.create_Hij_and_Bij(self.K_max, self.A_i)
                # initialize the tracking variable with this
                # initialize index tracker to -1
                E_K = np.min(sl.eigvals(Hij, Bij))
                idx_of_A_K_m = -1
                # generate Script_N candidates for the matrix currently at index K in self.A_i
                vector_set = self.generate_set_A_refine(K)
                # iterate through the candidates
                for n in range(self.script_N):
                    # generate Hamiltonian and Overlap matrices for the candidate
                    Hij, Bij = self.create_Hij_and_Bij(K, vector_set[n])
                    # calculate the lowest eigenvalue of the candidate
                    E_K_n = np.min(sl.eigvals(Hij, Bij))
                    # overwrite lowest eigenvalue if current eigenvalue is smaller
                    if E_K_n < E_K:
                        E_K = E_K_n
                        idx_of_A_K_m = n
                # finalize whichever candidate had the lowest eigenvalue, but leave unchanged if no candidate was lower that previous
                self.A_i = vector_set[idx_of_A_K_m] if idx_of_A_K_m != -1 else self.A_i
                # print to monitor progress of code
                print("K:", K, "E_K:", E_K)

    # method that takes the masses information from the class and outputs an list of reduced masses
    # runs only once
    def masses_to_reduced(self):
        if self.N < 2:
            raise ValueError("At least two masses are required to compute reduced masses.")

        reduced_ms = []

        for i in range(self.N - 1):
            m_i_plus_1 = self.ms[i + 1]
            m_12_to_i = self.cum_ms[i]
            m_12_to_i_plus_1 = self.cum_ms[i + 1]
            mu_i = (m_i_plus_1 * m_12_to_i) / m_12_to_i_plus_1
            reduced_ms.append(mu_i)

        return reduced_ms

    # method that takes the position information and generates N-1 jacobi coordinates (sans CoM)
    # uses Uij matrix which is generated later in the code
    # runs only once
    def positions_to_jacobi(self):
        if self.N < 2:
            raise ValueError("At least two particles are required to compute Jacobi coordinates.")
        U = self.generate_uij()
        positions = self.rs
        jacobi_coords = np.dot(U,positions)

        return jacobi_coords[:-1]

    # generates a random (N-1)x(N-1) matrix A by using a uniform rng to make a (N-1)x(N-1) matrix M
    # then multiplying M by its transpose to get a, which is semi-positive-definite and symmetric
    # runs a very large number of times
    def generate_matrix_A(self):
        if self.N <= 1:
            raise ValueError("Number of particles (N) must be greater than 1.")

        #mean = (self.bmin + self.bmax) / 2
        #std = 0.1 * (self.bmax - self.bmin)
        #M = np.random.normal(loc=mean, scale=std, size=(self.dim, self.dim))

        M = np.random.uniform(self.bmin, self.bmax, size=(self.dim, self.dim))

        A = M.T @ M

        if A.shape == ():
            A = A.reshape(1, 1)

        #A += epsilon * np.eye(self.dim)

        return A

    # generates what we call a vector set, which can be considered a 2-d array of A matrices
    # runs only in the Generating Phase
    # each row is a candidate for the SVM
    # all columns except for the last one are the same
    # runs a large number of times
    def generate_set_A(self, K):
        vector_set = np.empty((self.script_N, K, self.dim, self.dim))
        for i in range(self.script_N):
            # handles the edge case of inserting the very first element into copies of self.A_i
            if K == 1:
                vector_set[i] = self.generate_matrix_A()
            # handles the general case
            else:
                vector_set[i] = np.append(self.A_i, self.generate_matrix_A().reshape(1, self.dim, self.dim), axis=0)
        return vector_set

    # equivalent of generate_set_A() for the Refining Phase
    # replaces the value in the position K
    # runs a large number of times
    def generate_set_A_refine(self, K):
        vector_set = np.empty((self.script_N, self.K_max, self.dim, self.dim))
        for i in range(self.script_N):
            A_K = self.A_i.copy()
            A_K[K-1] = self.generate_matrix_A()
            vector_set[i] = A_K
        return vector_set

    # generates Uij matrix
    # uses the definition in the SVM paper (compared to the textbook)
    # runs twice
    def generate_uij(self):
        U = np.zeros((self.N, self.N))
        for i in range(self.N - 1):
            for j in range(i + 1):
                U[i, j] = self.ms[j] / self.cum_ms[i]
        for i in range(self.N - 2):
            U[i, i + 1] = -1.0
        for i in range(self.N):
            U[self.N-1, i] = self.ms[i] / self.cum_ms[self.N-1]
        return U

    # generates Bijk matrix using Uij
    # runs only once
    def generate_bijk(self):
        U = self.generate_uij()

        if np.linalg.det(U) == 0:
            raise ValueError("Matrix U must be invertible.")

        U_inv = np.linalg.inv(U)

        dim = U.shape[0]

        B = np.zeros((dim, dim, dim))

        for i in range(dim):
            for j in range(dim):
                for k in range(dim):
                    B[i, j, k] = U_inv[i, k] - U_inv[j, k]

        return B

    # generates the Hamiltonian and Overlap matrices for individual candidates
    # uses the BasisPair class defined below
    def create_Hij_and_Bij(self, K, A_K):
        Hij = np.zeros((K, K))
        Bij = np.zeros((K, K))

        for i in range(K):
            for j in range(K):
                BP = BasisPair(self.xs, self.mus, A_K[i], A_K[j], self.N, self.B, self.gauss_params)
                Hij[i, j] = BP.hamiltonian()
                Bij[i, j] = BP.overlap
        return Hij, Bij

class BasisPair:

    # This class' purpose is to abstract away all the math that is needed to find the Overlap and Hamiltonian matrices for one pair of A matrices

    def __init__(self, xs, mus, A, Ap, N, B, gauss_params):
        self.xs = xs
        self.mus = mus
        self.A = A
        self.Ap = Ap
        self.N = N
        self.B = B
        self.gauss_params = gauss_params

        self.overlap = self.generate_overlap()
        self.Lambda = self.generate_lambda()
        self.p = self.generate_pij()

    # generates the value < G_A | G_A' >
    def generate_overlap(self):
        a = (2*np.pi)**(self.N-1)
        # handles edge case where A and A' are 1x1 matrices
        if self.A.shape == (1, 1):
            b = self.A[0, 0] + self.Ap[0, 0]
        # handles general case
        else:
            b = np.linalg.det(self.A + self.Ap)
        return np.sqrt(a/b)

    # generates the lambda matrix used for kinetic energy
    def generate_lambda(self):
        Lambda = np.zeros((self.N-1, self.N-1))
        for i in range(self.N-1):
            Lambda[i, i] = 1/(2*self.mus[i])
        return Lambda

    # calculates the kinetic energy half of the Hamiltonian
    def kinetic_energy(self):
        return (1/2)* np.trace( self.A @ np.linalg.inv(self.A+self.Ap) @ self.Ap @ self.Lambda) *self.overlap

    # generates a p_ij matrix used for potential energy
    def generate_pij(self):
        pij_matrix = np.zeros((self.N, self.N))
        AApinv = np.linalg.inv(self.A + self.Ap)
        for j in range(self.N):
            for i in range(j):
                Bij = self.B[i, j, :]
                for k in range(self.N-1):
                    for l in range(self.N-1):
                        pij_matrix[i, j] += Bij[k] * AApinv[k, l] * Bij[l]
        return pij_matrix

    # a general integration method for potential energy
    def vpij(self, i, j):
        # a maximum range that should approximate infinity for all practical purposes
        maxrange = 100
        return np.sqrt(1 / (2*np.pi*self.p[i, j])) * si.quad(lambda r: V(r) * np.exp(- r**2/(2*self.p[i, j])), 0, maxrange)[0]

    # a specialized integration method for potential energy
    # specialized for the gaussian potential, analytical solution
    # the values seem to not match up to the general case -- todo fix
    def vpij_gaussian(self, i, j):
        V0, R = self.gauss_params
        return V0/2 * np.sqrt( 2*np.pi* R**2 *self.p[i, j] / (R**2 + self.p[i, j])) # assumes integrated over positive r

    # calculates the potential energy half of the Hamiltonian, one pair of particles at a time, summing over them
    def potential_energy(self):
        is_gaussian = self.gauss_params is not None # boolean
        total_V = 0
        for j in range(self.N):
            for i in range(j):
                total_V += self.overlap * (self.vpij_gaussian(i, j) if is_gaussian else self.vpij(i, j)) # chooses which integration method to use
        return total_V

    # sums the two halfs of the Hamiltonian and returns it
    def hamiltonian(self):
        return self.kinetic_energy() + self.potential_energy()

svm = SVM([1, 1], [1, 1], V, 30, 15, 3, -10, 10)

svm.main()